version: '3'
services:
  backend:
    container_name: backend_php
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      PHP_XDEBUG_REMOTE_PORT: "${PHP_XDEBUG_REMOTE_PORT}"
      PHP_XDEBUG_REMOTE_HOST: "${PHP_XDEBUG_REMOTE_HOST}"
    volumes:
      - ${BACKEND_PATH}:/app
    ports:
      - "5000:8080"
  web:
    container_name: web_php
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      PHP_XDEBUG_REMOTE_PORT: "${PHP_XDEBUG_REMOTE_PORT}"
      PHP_XDEBUG_REMOTE_HOST: "${PHP_XDEBUG_REMOTE_HOST}"
    volumes:
      - ${WEB_PATH}:/app
    ports:
      - "5001:8080"
  db:
    container_name: allchords_mysql
    image: "mysql:8"
    expose:
      - "3306"
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
